# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [33]:
dataset = pd.read_csv('Covid19.csv')
X = dataset.iloc[:,2:-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [35]:
print(X_train)

[[1.1269e+02 2.7243e+02 3.2420e+01 ... 0.0000e+00 0.0000e+00 3.2000e+02]
 [7.3360e+01 1.1002e+02 8.4580e+01 ... 1.5800e+01 2.3000e-01 2.6200e+02]
 [1.0258e+02 1.0302e+02 6.1900e+01 ... 5.7860e+01 0.0000e+00 2.7200e+02]
 ...
 [6.3000e+01 2.2640e+02 6.5000e-01 ... 1.6100e+01 2.5900e+00 1.5200e+02]
 [4.6914e+02 4.6180e+01 1.3220e+01 ... 2.0420e+01 7.0800e+00 1.5500e+02]
 [2.5560e+01 1.5137e+02 2.0870e+01 ... 2.1500e+00 4.1000e-01 3.6200e+02]]


In [36]:
print(y_train)

[0. 0. 0. ... 1. 1. 0.]


In [37]:
print(X_test)

[[1.1801e+02 3.1690e+02 1.9690e+01 ... 1.3610e+01 9.8000e-01 4.1700e+02]
 [3.6380e+01 9.6880e+01 2.2140e+01 ... 1.5350e+01 2.1000e-01 3.1800e+02]
 [8.4910e+01 7.6930e+01 2.0420e+01 ... 3.1200e+00 0.0000e+00 1.4400e+02]
 ...
 [7.3300e+01 7.7840e+01 1.0510e+01 ... 7.5300e+00 4.4700e+00 1.9900e+02]
 [1.3260e+02 3.4811e+02 2.3880e+01 ... 8.0300e+00 5.0000e-02 1.9400e+02]
 [4.6840e+01 1.8870e+02 3.9900e+00 ... 0.0000e+00 1.3000e-01 2.6100e+02]]


In [38]:
print(y_test)

[0. 0. 1. ... 1. 1. 0.]


## Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
print(X_train)

[[ 1.17566462e-01  4.81544586e-01 -2.97907008e-02 ... -6.29680505e-01
  -3.71160111e-01  7.24859957e-01]
 [-3.40720505e-01 -6.90630020e-01  1.14910947e+00 ... -1.70764532e-01
  -3.36605966e-01  2.91636443e-01]
 [-2.38807383e-04 -7.41151676e-01  6.36504869e-01 ...  1.05088141e+00
  -3.71160111e-01  3.66330152e-01]
 ...
 [-4.61438862e-01  1.49328607e-01 -7.47843965e-01 ... -1.62050938e-01
   1.79496064e-02 -5.29994359e-01]
 [ 4.27104700e+00 -1.15138753e+00 -4.63741682e-01 ... -3.65751781e-02
   6.92506606e-01 -5.07586247e-01]
 [-8.97702886e-01 -3.92191377e-01 -2.90839338e-01 ... -5.67233078e-01
  -3.09563592e-01  1.03857354e+00]]


In [41]:
print(X_test)

[[ 0.17955697  0.80250145 -0.31750924 ... -0.23437377 -0.22392941
   1.44938894]
 [-0.77162445 -0.78546639 -0.26213529 ... -0.18383492 -0.33961067
   0.70992121]
 [-0.20613585 -0.92945311 -0.30101006 ... -0.53905912 -0.37116011
  -0.58974933]
 ...
 [-0.34141965 -0.92288529 -0.52499206 ... -0.41096929  0.30039218
  -0.17893393]
 [ 0.34956477  1.02775587 -0.22280848 ... -0.39644663 -0.36364834
  -0.21628078]
 [-0.64974086 -0.1227666  -0.67235458 ... -0.6296805  -0.35162951
   0.28416707]]


## Training the K-NN model on the Training set

In [42]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Predicting a new result

In [43]:
print(classifier.predict(sc.transform([[300.21,286.05,32.28,63.06,27.87,56.35,1.32,16.08,13.54,0.56,0,2.42,276]])))

[0.]
